import { createActions } from 'reduxsauce';

export const { Types, Creators } = createActions({
  createCategory: ['data'],
  createCategoryFailure: null,
  createCategorySuccess: ['category'],
  createVideo: ['data'],
  createVideoFailure: null,
  createVideoSuccess: ['video'],
  confirmDeleteCategory: ['categoryId'],
  deleteCategory: ['categoryId'],
  deleteCategoryFailure: null,
  deleteCategorySuccess: ['categoryId'],
  deleteVideo: ['categoryId', 'videoId'],
  deleteVideoFailure: null,
  deleteVideoSuccess: ['videoId'],
  editCategory: ['categoryId'],
  editVideo: ['videoId'],
  likeVideo: ['videoId'],
  unlikeVideo: ['videoId'],
  viewVideo: ['videoId'],
  filterVideos: ['query'],
  getCategoriesAttempt: null,
  getAllCategoriesAttempt: null,
  getCategoriesFailure: null,
  getCategoriesSuccess: ['categories'],
  getVideoCategoryAttempt: ['categoryId'],
  getVideoCategorySuccess: ['category'],
  getVideoCategoryFailure: null,
  getVideosAttempt: ['categoryId'],
  getVideosFailure: null,
  getVideosSuccess: ['videos'],
  reportVideoFlag: ['videoId', 'user'],
  resetCategories: null,
  resetVideos: null,
  resetVideosFilter: null,
  selectSector: ['sectorId'],
  selectCategory: ['categoryId'],
  selectSubCategory: ['subCategoryId'],
  toggleAddCategory: null,
  toggleAddVideo: null,
  updateCategory: ['data'],
  updateCategoryFailure: null,
  updateCategorySuccess: ['category'],
  updateVideo: ['data'],
  updateVideoFailure: null,
  updateVideoSuccess: ['video'],
  setImagePreview: ['imagePreview'],
  getAllVideosAttempt: null,
  getAllVideosFailure: null,
  getAllVideosSuccess: ['videos'],
  toggleCategoryMenu: null,
  setEditingSubCategory: ['data'],
  setSelectedHeader: ['data'],

  getVideoAllQualificationsAttempt: null,
  getVideoAllQualificationsSuccess: ['qualifications'],
  getVideoAllQualificationsFailure: ['errorCode'],
  setVideoQualifications: ['qualifications']
});
