export default {
  activated: true,
  address_id: 0,
  centres: [
    {
      centre_id: 1301,
      centre_name: 'Digital Educational Publications',
      centre_number: 'DEP1000',
      organisation_type: 'employer',
      cloudinary_file_id: 'testing/ntxscistw5cxgmfakjsg',
      contact_email: 'centre-admin@depub.co.uk',
      centre_contact_first_name: 'Albus',
      centre_contact_last_name: 'Dumbledore',
      roles: ['CENTRE_ADMIN_ROLE'],
      role_ids: 1,
      completed: 1,
      website: 'test.com',
      contact_number: '07784408189',
      address_line_1: '1 Tetbury PLace',
      address_line_2: '',
      postcode: 'N1 0HQ',
      city: 'Islington',
      country: 'United Kingdom'
    },
    {
      centre_id: 1443,
      centre_name: 'Hogwarts LTD',
      centre_number: 'TEST123',
      organisation_type: 'employer',
      cloudinary_file_id: null,
      contact_email: 'cerid@lillemap.net',
      centre_contact_first_name: 'Harry',
      centre_contact_last_name: 'Potter',
      roles: ['CENTRE_TUTOR_ROLE'],
      role_ids: 4,
      completed: 1,
      website: 'www.test.pl',
      contact_number: '0756574773',
      address_line_1: 'fsds',
      address_line_2: 'sdffsdfsdsd',
      postcode: 'N17 6EB',
      city: 'sdf',
      country: 'Poland'
    },
    {
      centre_id: 1627,
      centre_name: 'Coded Media Ltd',
      centre_number: 'CM1000',
      organisation_type: 'employer',
      cloudinary_file_id: null,
      contact_email: 'centre@codedmedia.co.uk',
      centre_contact_first_name: 'Severus',
      centre_contact_last_name: 'Snape',
      roles: ['CENTRE_LEARNER_ROLE'],
      role_ids: 5,
      completed: 1,
      website: 'www.codedmedia.co.uk',
      contact_number: '07841424609',
      address_line_1: '79 Thornbury Road',
      address_line_2: '',
      postcode: 'TW7 4NL',
      city: 'Isleworth',
      country: 'United Kingdom'
    }
  ],
  cloudinary_file_id: 'testing/iujriw0hpyfmcrmvdjs5',
  completed: 0,
  date_of_birth: '1980-01-01',
  email: 'bogdan@depub.co.uk',
  facebook: '',
  facebook_id: null,
  first_name: 'Bogdan',
  gender: 1,
  geolocation: null,
  join_date: '2017-01-04',
  language: 'english',
  last_activity: '2017-04-26 12:35:49',
  last_activity_unix: 1493210149,
  last_external_login: 0,
  last_name: 'Protsenko',
  last_visit: '2017-04-25',
  linkedin: '',
  member_id: 1319,
  middle_name: null,
  nationality_id: null,
  notifications_counts: {
    friend_request: 31,
    message: 198,
    system: 0,
    tutor_assignment: 6
  },
  personal_statement: null,
  photo: 'testing/iujriw0hpyfmcrmvdjs5',
  pinterest: '',
  reset_code: '',
  roles: ['SUPER_ADMIN_ROLE', 'SITE_ADMIN_ROLE', 'MEMBER_ROLE'],
  screen_name: 'Bogdan Protsenko',
  timezone: 'Europe/London',
  twitter: '',
  uk_mobile_number: '0748939956',
  unverified_email: false,
  verification_email_key: null,
  website: null,
  permissions: {
    '/test-resource': [],
    '/workbooks-builder': [
      'create_sector',
      'modify_sector',
      'create_qualification',
      'modify_qualification',
      'create_unit',
      'modify_unit',
      'create_qualification_type',
      'modify_qualification_type',
      'create_workbook',
      'modify_workbook'
    ],
    '/centre': ['modify'],
    '/member': ['view'],
    '/centre/1301': [
      'create',
      'modify',
      'create_sector',
      'modify_sector',
      'create_qualification',
      'modify_qualification',
      'create_unit',
      'modify_unit',
      'create_qualification_type',
      'modify_qualification_type',
      'create_workbook',
      'modify_workbook'
    ],
    '/centre/1443': {
      '1': 'modify'
    },
    '/centre/1627': {
      '1': 'modify'
    }
  }
};
