const USER_ROLE = {
  SUPER_ADMIN_ROLE: 'SUPER_ADMIN_ROLE',
  SITE_ADMIN_ROLE: 'SITE_ADMIN_ROLE',
  AUTHOR_ROLE: 'AUTHOR_ROLE',
  MEMBER_ROLE: 'MEMBER_ROLE',
  LEARNER_ROLE_ID: 'LEARNER_ROLE_ID',
  EDUCATOR_ROLE_ID: 'EDUCATOR_ROLE_ID'
};

export default USER_ROLE;
