import { createActions } from 'reduxsauce';

export const { Types, Creators } = createActions({
  chatApiAttempt: null,
  chatApiFinished: null,
  getChatsAttempt: null,
  getChatsSuccess: ['chats'],
  getChatsFailure: null,
  getMediaAttempt: ['member_id'],
  getMediaSuccess: ['member_id', 'list'],
  getMediaFailure: null,
  startChatAttempt: ['participants', 'title', 'routeChange', 'file'],
  startChatSuccess: ['chat'],
  startChatFailure: null,
  deleteChatAttempt: ['chat_id'],
  deleteChatSuccess: ['chat_id'],
  leaveChatAttempt: ['chat_id'],
  leaveChatSuccess: ['chat_id'],
  updateChatAttempt: ['chat_id', 'title', 'file'],
  updateChatSuccess: ['chat_id'],
  updateChatFailure: null,
  chatParticipantsAttempt: null,
  chatParticipantsSuccess: ['participants'],
  chatFilterChanged: ['filter'],
  chatMarkAsReadAttempt: ['chat'],
  chatMarkAsReadSuccess: ['chat_id'],
  chatSelected: ['chat_id'],
  chatUpdated: ['chat_id', 'data'],
  changeChatLayout: ['layout'],
  participantSelected: ['member_id'],
  participantsDeleted: ['chat_id', 'deleted_participants'],
  panelOpen: ['open'],

  getContactsAttempt: null,
  getContactsSuccess: ['contacts'],
  getContactsFailure: ['errorCode'],
  contactsFilterChanged: ['newFilter'],
  toggleContact: ['contact', 'multi'],
  selectContacts: ['selectedContacts'],

  getMessagesAttempt: ['chat_id'],
  getMessagesSuccess: ['messages', 'chat_id'],
  getMessagesFailure: null,
  addPendingMessage: ['message'],
  removePendingMessage: ['message_id'],
  sendMessageAttempt: ['chat_id', 'message'],
  sendMessageSuccess: ['message', 'pending_message_id'],
  sendMessageFailure: null,
  removeChatMessages: ['chat_id'],
  receiveMessage: ['message', 'unread'],
  markMessagesRead: ['chat_id'],
  selectMessageMode: ['mode'],
  toggleDeleteMessage: ['msg_id', 'checked'],
  clearDeleteMessages: null,
  deleteMessages: null,
  removeMessages: ['msgs'],

  updateSearchTerm: ['searchTerm'],

  updateCreatingChat: ['creatingChat']
});
